spring:
  datasource:
    hikari:
      maximum-pool-size: 20

foo:
  datasource:
    url: jdbc:h2:mem:foo
    driver-class-name: org.h2.Driver

bar:
  datasource:
    url: jdbc:h2:mem:bar
    driver-class-name: org.h2.Driver
